---
- hosts: all
  tasks:
  - name: nofile soft ulimit
    pam_limits:
      domain: '*'
      limit_type: soft
      limit_item: nofile
      value: 10000
  - name: nofile hard limit
    pam_limits:
      domain: '*'
      limit_type: hard
      limit_item: nofile
      value: 10000


